name: CI

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  label-check:
    name: Label Check
    uses: ApolloAutomation/Workflows/.github/workflows/label-check.yml@main

  ci:
    name: CI
    uses: ApolloAutomation/Workflows/.github/workflows/esphome-ci.yml@main
    with:
      yaml-files: |
        Integrations/ESPHome/PLT-1.yaml
        Integrations/ESPHome/PLT-1_BLE.yaml
        Integrations/ESPHome/PLT-1B.yaml
        Integrations/ESPHome/PLT-1B_BLE.yaml
        Integrations/ESPHome/PLT-1_Minimal.yaml
        Integrations/ESPHome/PLT-1B_Minimal.yaml

