name: Weekly Firmware Build

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Building ${{ matrix.file }} / ESPHome ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Integrations/ESPHome/PLT-1.yaml
          - Integrations/ESPHome/PLT-1_BLE.yaml
          - Integrations/ESPHome/PLT-1B.yaml
          - Integrations/ESPHome/PLT-1B_BLE.yaml
          - Integrations/ESPHome/PLT-1_Minimal.yaml
          - Integrations/ESPHome/PLT-1B_Minimal.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7.0.0
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}