name: Weekly Firmware Build

on:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  build:
    name: Weekly Build
    uses: ApolloAutomation/Workflows/.github/workflows/esphome-ci.yml@main
    with:
      yaml-files: |
        Integrations/ESPHome/PLT-1.yaml
        Integrations/ESPHome/PLT-1_BLE.yaml
        Integrations/ESPHome/PLT-1B.yaml
        Integrations/ESPHome/PLT-1B_BLE.yaml
        Integrations/ESPHome/PLT-1_Minimal.yaml
        Integrations/ESPHome/PLT-1B_Minimal.yaml

